"""auto datetime migration

Revision ID: 1e760eae6fdb
Revises: 76da7d25f71b
Create Date: 2024-01-30 20:20:23.783873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e760eae6fdb'
down_revision = '76da7d25f71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
