"""Three migration

Revision ID: 4c266fe5acc9
Revises: 6008c0155cc9
Create Date: 2024-01-30 11:25:27.558639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c266fe5acc9'
down_revision = '6008c0155cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
