"""Two migration

Revision ID: 6008c0155cc9
Revises: 48b01a0f5b70
Create Date: 2024-01-30 11:22:54.860630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6008c0155cc9'
down_revision = '48b01a0f5b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
