"""User time migration

Revision ID: 76da7d25f71b
Revises: 5ded1d99919a
Create Date: 2024-01-30 17:04:41.360384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76da7d25f71b'
down_revision = '5ded1d99919a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
