"""auto datetime 4 migration

Revision ID: 802bfd4208e7
Revises: 948801534de7
Create Date: 2024-02-03 15:00:51.171220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802bfd4208e7'
down_revision = '948801534de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
